# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  NODE_OPTIONS: --max_old_space_size=4096

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install

      - run: yarn lint

  lib:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        angular-version: [8.1.x, 9.0.x, 10.0.x, 10.1.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v2
        with:
          angular_version: ${{ matrix.angular-version }}
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install

      - run: yarn build:lib
      - run: yarn test:lib:headless

  app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        angular-version: [8.1.x, 9.0.x, 10.0.x, 10.1.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v2
        with:
          angular_version: ${{ matrix.angular-version }}
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install

      - run: yarn build
      - run: yarn test:headless
      - run: yarn e2e
